import Link from 'next/link';
export const metadata = { title: 'Motherboard Academy — Builder Portal' };
const rooms=[['START HERE','Welcome + Builder Thesis','Welcome video, Builder Thesis worksheet, live schedule, how to ship.'],['THE VAULT','Eight Build Weeks','Pre-recorded lessons, decks, workbooks, checklists — unlocked week by week.'],['LIVE SESSIONS','Tuesdays + Thursdays, 5:30 PM PT','Build Class + Agent Lab links and replays, organized by week.'],['AI COPYWRITER','Motherboard AI Copywriter','Tool access, setup guide, voice-training template, prompt vault.'],['MASTERY CHECKS','Eight tests','80% to pass. Unlimited retakes. Confidence, not gatekeeping.'],['SHIP LIST','Weekly proof of work','One implementation submission per week. Visible. Reviewed.'],['BUILDERS','Motherboard Builders','The community. You are not here to consume information. You are here to ship proof.'],['CERTIFICATION','Motherboard Builder Certification','Issued after the Week 8 capstone: offer live, workflow demoed, portfolio reviewed.']];
const weeks=[['WEEK 01','Claim Your Builder Thesis'],['WEEK 02','Build the Offer Worth Buying'],['WEEK 03','Positioning That Commands Attention'],['WEEK 04','The Motherboard AI Copywriter'],['WEEK 05','Build Your Digital Workforce'],['WEEK 06','The Ownership Engine'],['WEEK 07','Demand, Content, and Conversion'],['WEEK 08','Ship Week + Marketplace Readiness']];
export default function Portal(){return <main><nav><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><Link className="textlink" href="/">← Home</Link></nav>
<section className="hero"><p className="eyebrow">MOTHERBOARD ACADEMY • BUILDER PORTAL</p><h1>Build power<br/><em>around real life.</em></h1><p className="lede">You are not here to consume information. You are here to ship proof. This is the room enrolled Builders receive: the Vault, the live schedule, the AI Copywriter, Mastery Checks, the Ship List, and the community.</p></section>
<section className="build"><p className="eyebrow">THE ROOMS</p><h2>Every room has a job.</h2><div className="buildgrid">{rooms.map(([b,t,d])=><article key={b}><b>{b}</b><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="method"><p className="eyebrow">THE VAULT</p><h2>Eight Build Weeks.</h2><div className="methodgrid weeksgrid">{weeks.map(([w,t])=><article key={w}><b>{w}</b><h3>{t}</h3><p>Lesson · Deck · Workbook · Checklist · Mastery Check · Replays</p></article>)}</div></section>
<section className="cta"><p className="eyebrow">ENROLLED BUILDERS ONLY</p><h2>Less searching.<br/>More building.</h2><p>Access opens with the Founding Builder Cohort on Tuesday, October 6. Enrollment opens live at the masterclass.</p><Link className="button light" href="/masterclass">Save your masterclass seat <span>↗</span></Link></section>
<footer><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><p>Build power around real life.</p><div><Link href="/legal">Terms + Privacy</Link></div></footer></main>}
