import Link from 'next/link';
import RegisterForm from '../components/RegisterForm';
export const metadata = { title: 'The Motherboard Agentic AI Masterclass — Tuesday 5:30 PM PT', description: 'Free live masterclass: how women build AI agents, offers, systems, and ownership around real life.' };
const learn=['See the difference between using AI and building an agentic AI workforce.','Identify your Intelligence Asset — the knowledge, story, or skill that can become an offer this month.','Learn the three systems that create leverage before you have a team, audience, or budget.','Watch the Motherboard AI Copywriter work live — and why it keeps women from sounding generic.','See the real path from builder → paid offer → marketplace.','Meet Motherboard Academy: the room, the method, the tools, and the founding cohort.'];
export default function Masterclass(){return <main><div className="topbar">FREE LIVE MASTERCLASS • TUESDAY, SEPT 29 • 5:30 PM PT</div><nav><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><Link className="textlink" href="/">← Home</Link></nav>
<section className="hero grid-bg herosplit"><div><p className="eyebrow">THE MOTHERBOARD AGENTIC AI MASTERCLASS</p><h1>Build your digital workforce.<br/><em>Build what you own.</em></h1><p className="lede">How women build AI agents, offers, systems, and ownership around real life — without becoming developers or waiting for more time.</p></div><RegisterForm/></section>
<section className="statement"><p className="eyebrow">IN 90 MINUTES YOU WILL</p><h2>Stop using AI.<br/>Start building with it.</h2><div className="list inklist">{learn.map((l,i)=><p key={i}><b>0{i+1}</b> {l}</p>)}</div></section>
<section className="split dark"><div><p className="eyebrow">THE MOTHERBOARD METHOD</p><h2>AI is the workforce. You are the asset. Ownership is the outcome.</h2></div><div className="list"><p>01 — Your Intelligence Asset: the expertise, story, and problems you already solve.</p><p>02 — Your Digital Workforce: agents and workflows for research, content, sales, ops, and delivery.</p><p>03 — Your Ownership Engine: the offer, path, and system that turns work into revenue.</p></div></section>
<section className="build"><p className="eyebrow">WHO IT IS FOR</p><h2>Women with a skill, an idea,<br/>an audience, or a business.</h2><div className="buildgrid"><article><b>FOR</b><h3>Mothers</h3><p>Who need leverage, not another obligation.</p></article><article><b>FOR</b><h3>Consultants + coaches</h3><p>Who want a digital workforce behind their expertise.</p></article><article><b>FOR</b><h3>Creators + educators</h3><p>Who want to own the systems they build, not rent them.</p></article><article><b>NOT FOR</b><h3>Prompt collectors</h3><p>If you want another prompt pack, this is not the room.</p></article></div></section>
<section className="manifesto"><p className="eyebrow">FROM THE FOUNDER</p><h2>I did not build Motherboard in a week.</h2><p>I have been building the systems, the agents, the AI Copywriter, the curriculum, and the infrastructure behind it for a long time. It needed a name that told the truth about who it is for.</p><p>— T. Evans, Founder</p></section>
<section className="cta"><p className="eyebrow">TUESDAY, SEPTEMBER 29 • 5:30–7:00 PM PT • LIVE ON GOOGLE MEET</p><h2>Save your seat.<br/>It is free.</h2><RegisterForm light compact/></section>
<footer><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><p>Build power around real life.</p><div><Link href="/legal">Terms + Privacy</Link><Link href="/about">About</Link></div></footer></main>}
