import Link from 'next/link';
export const metadata = { title: 'Motherboard Academy — The Agentic AI Builder Program for Women', description: 'Eight weeks. Live Tuesdays + Thursdays, 5:30 PM PT. Build a digital workforce around your intelligence — and own what you build.' };
const weeks=[['01','Claim Your Builder Thesis','Builder Thesis + 8-week Build Plan'],['02','Build the Offer Worth Buying','Offer Blueprint + Ideal Buyer + price'],['03','Positioning That Commands Attention','Positioning sheet, pitch, bio, key messages'],['04','The Motherboard AI Copywriter','Configured Copywriter + 30 content angles'],['05','Build Your Digital Workforce','2–3 working agentic workflows'],['06','The Ownership Engine','Live sales page or booking / checkout flow'],['07','Demand, Content, and Conversion','30-day content plan + launch scripts + DM flow'],['08','Ship Week + Marketplace Readiness','Live offer + workflow demo + Builder Portfolio']];
const tiers=[{name:'Builder Access',price:'$497',plan:'or 2 × $275',items:['The Vault: all pre-recorded Build Weeks','Decks, workbooks, templates, checklists','Mastery Checks + Builder Certification path','Motherboard AI Copywriter framework','Replay library']},{name:'Live Builder',price:'$1,497',plan:'or 3 × $549 · 6 × $299',hot:true,items:['Everything in Builder Access','Live Build Classes — Tuesdays 5:30 PM PT','Agent Labs — Thursdays 5:30 PM PT','Feedback on your real work','Motherboard Builders community','Every session recorded']},{name:'Build Lab',price:'$2,997',plan:'or 3 × $1,099 · 6 × $599',items:['Everything in Live Builder','Small-group hot seats','Offer + agent audits','Priority feedback','Motherboard Exchange consideration']}];
export default function Academy(){return <main><div className="topbar">FOUNDING BUILDER COHORT • STARTS TUESDAY, OCTOBER 6 • FOUNDING PRICING ENDS OCTOBER 4</div><nav><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><Link className="textlink" href="/">← Home</Link></nav>
<section className="hero grid-bg"><p className="eyebrow">MOTHERBOARD ACADEMY • THE AGENTIC AI BUILDER PROGRAM FOR WOMEN</p><h1>Build a digital workforce<br/><em>around your intelligence.</em></h1><p className="lede">Eight weeks. Live Build Classes on Tuesdays, Agent Labs on Thursdays, 5:30 PM PT — every session recorded. Pre-recorded lessons, decks, tests, templates, the Motherboard AI Copywriter, and feedback on your real work.</p><div className="actions"><Link className="button" href="/masterclass">Start with the free masterclass <span>↗</span></Link><a className="textlink" href="#pricing">See founding pricing →</a></div><div className="signal"><i></i> LEARN IT TUESDAY. BUILD IT BEFORE THURSDAY. SHIP IT BEFORE NEXT WEEK.</div></section>
<section className="statement"><p className="eyebrow">WHAT YOU LEAVE WITH</p><h2>Not more information.<br/>Real infrastructure.</h2><div className="list inklist"><p>— A clear offer with a price and a buyer.</p><p>— One live sales page, checkout path, or booking flow.</p><p>— Your trained Motherboard AI Copywriter.</p><p>— Two to three repeatable agentic workflows.</p><p>— A 30-day content and demand plan.</p><p>— A Builder Portfolio showing what you built — and Motherboard Builder Certification.</p></div></section>
<section className="method"><p className="eyebrow">THE EIGHT BUILD WEEKS</p><h2>Learn it. Build it.<br/>Ship it. Own it.</h2><div className="methodgrid weeksgrid">{weeks.map(([n,t,o])=><article key={n}><b>WEEK {n}</b><h3>{t}</h3><p>{o}</p></article>)}</div></section>
<section className="split dark"><div><p className="eyebrow">THE WEEKLY RHYTHM</p><h2>Two live rooms a week. Everything recorded.</h2></div><div className="list"><p><b>Tuesday 5:30–7:00 PM PT</b> — Build Class. The week's method, the core asset, what “done” looks like.</p><p><b>Thursday 5:30–7:00 PM PT</b> — Agent Lab + Power Session. Live builds, hot seats, agent demos, shipping.</p><p><b>On demand</b> — The Vault. Pre-recorded lessons, decks, workbooks, checklists, Mastery Checks, replays.</p><p><b>Between sessions</b> — Ship List. One implementation submission per week.</p></div></section>
<section className="build" id="pricing"><p className="eyebrow">FOUNDING COHORT PRICING</p><h2>Choose your room.</h2><div className="tiers">{tiers.map(t=><article key={t.name} className={t.hot?'tier hot':'tier'}>{t.hot&&<span className="tag">MOST BUILDERS CHOOSE THIS</span>}<b>{t.name.toUpperCase()}</b><h3>{t.price}</h3><p className="plan">{t.plan}</p><ul>{t.items.map(i=><li key={i}>{i}</li>)}</ul><Link className={t.hot?'button':'button darkbutton'} href="/masterclass">Enrollment opens at the masterclass <span>↗</span></Link></article>)}</div><p className="finenote">Founding prices close Sunday, October 4 at 11:59 PM PT. Standard pricing after: $997 · $2,497 · $4,997. Refund terms are published on the checkout page.</p></section>
<section className="manifesto"><p className="eyebrow">ALREADY BUILT. READY TO ENTER.</p><h2>This is not a course being built. It is a room being opened.</h2><p>The curriculum, the agent library, the Motherboard AI Copywriter, the decks, the tests, the workflows, and the live implementation rooms already exist. Motherboard is the name that tells the truth about who they are for.</p></section>
<section className="cta"><p className="eyebrow">FOUNDING COHORT • OCTOBER 6 – NOVEMBER 26</p><h2>Your work deserves<br/>a system.</h2><p>Enrollment opens live at the free masterclass on Tuesday, September 29 at 5:30 PM PT. Replay registrants receive the enrollment link the next morning.</p><Link className="button light" href="/masterclass">Save your masterclass seat <span>↗</span></Link></section>
<footer><Link className="logo" href="/">MOTHER<span>BOARD</span></Link><p>Build power around real life.</p><div><Link href="/legal">Terms + Privacy</Link><Link href="/about">About</Link></div></footer></main>}
